-- AlterTable
ALTER TABLE `reservation` ADD COLUMN `cancelledReason` VARCHAR(255) NULL,
    ADD COLUMN `rejectReason` VARCHAR(255) NULL,
    MODIFY `status` ENUM('PENDIENTE', 'ACEPTADA', 'RECHAZADA', 'CANCELADA', 'FINALIZADA', 'EXPIRADA') NOT NULL DEFAULT 'PENDIENTE';
