-- AlterTable
ALTER TABLE `reservation` ADD COLUMN `checkInAt` DATETIME(3) NULL,
    ADD COLUMN `checkInDeadline` DATETIME(3) NULL,
    ADD COLUMN `endedAt` DATETIME(3) NULL,
    ADD COLUMN `startedAt` DATETIME(3) NULL,
    MODIFY `status` ENUM('PENDIENTE', 'ACEPTADA', 'RECHAZADA', 'CANCELADA', 'FINALIZADA', 'EXPIRADA', 'CHECKIN_SOLICITADO', 'EN_CURSO') NOT NULL DEFAULT 'PENDIENTE';
